name: Deploy to AWS EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Git Checkout
      uses: actions/checkout@v3

    - name: SSH를 이용한 EC2 접속 및 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 10m  # 타임아웃을 10분으로 연장
        script: |
          cd /home/ec2-user/workspace/miniMes  # EC2에 프로젝트가 있는 경로
          git fetch origin main
          git reset --hard origin/main
          
          # --- 1. 프론트엔드(Node.js) 빌드 및 실행 ---
          cd frontend
          npm install
          npm run build
 
          # 빌드된 파일들을 스프링 부트의 static 폴더로 이동
          cp -r dist/* ../src/main/resources/static/
          cd ..

          # 백엔드 작업 하기 위해 다시 루트 폴더로 이동
          cd /home/ec2-user/workspace/miniMes

          # 기존에 돌고 있던 Java(Spring Boot) 프로세스 종료
          sudo fuser -k 8080/tcp || true
          sudo pkill -f 'java -jar' || true


          # --- 2. 백엔드(Spring Boot) 빌드 및 실행 ---
          echo "=== Backend Deploy Start ==="
        
          # Maven 빌드 (pom.xml 기준)
          mvn clean package -DskipTests
          nohup java -jar target/*.jar > backend.log 2>&1 &
          echo "=== Deploy Complete ==="
